version: '3.8'

services:
  frontend:
    container_name: stock-frontend-dev
    build:
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    command: npm start

  api:
    container_name: stock-api-dev
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - api/.env
    ports:
      - "${API_PORT}:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    command: npm run dev

  db:
    container_name: stock-db-dev
    ports:
      - "${DB_PORT}:5432"

  # Add any other development services here (e.g., backend, database) 