version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - stock-network

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    command: sh -c "npm install && npm start"
    ports:
      - "5010:5010"
    environment:
      - NODE_ENV=production
      - PORT=5010
      - DATABASE_URL=postgres://user:password@db:5432/stockdb
    depends_on:
      - db
    networks:
      - stock-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stockdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  postgres_data: 